source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-admin'
gem 'jekyll-tidy'
gem 'jekyll-github-metadata'
gem 'jekyll-minifier'
gem 'amp-jekyll'
gem 'github-pages'
gem 'jekyll-sitemap'
