const Members = [
  /*
      A definição da chave deve seguir a seguinte regra:
      - regra geral: usar o primeiro nome mais último sobrenome;
        - obs: caso o nome tenha algum sufixo, acrescentar a primeira letra do sufixo no final do nome;
      - exceção 1: usar o "nome de guerra" de professor da UnB (se houver);
      - exceção 2: usar o sobrenome se for um sobrenome já utilizado para se referir a pessoa. Exemplo: Patrão, Prado, Venzi e Kfouri.

      Obs.:
      - todos as letras minúsculas;
      - não usar acentos ou cedilha.
  */
        {
            key: "prado",
            name: "Daniel Prado",
            area: "Engenharia de Redes de Comunicação",
            role: "software",
            email: "daniel@gmail.com",
            pic: "",
            bio: "A cool person",
            lattes: "",
            linkedin: "meu linked-in",
            active: true
        },
        {
            key: "lucasmartins",
            name: "Lucas Martins",
            area: "Engenharia Elétrica",
            role: "software",
            email: "lmartins@gmail.com",
            pic: "",
            bio: "A cool person",
            lattes: "",
            linkedin: "meu linked-in",
            active: true
        },
        {
            key: "victorcampos",
            name: "Victor Campos",
            area: "Ciência da Computação",
            role: "software",
            email: "victor@gmail.com",
            pic: "",
            bio: "A strong person",
            lattes: "",
            linkedin: "meu linked-in",
            active: true,
        },
        {
            key: "lincolnbarbosa",
            name: "Lincoln Abreu",
            area: "Engenharia da Computação",
            role: "hardware",
            email: "abreu@gmail.com",
            pic: "",
            bio: "A smart person",
            lattes: "",
            linkedin: "meu linked-in",
            active: true
        },
        {
            key: "venzi",
            name: "Daniel G. V. Gonçalves",
            area: "Engenharia de Redes de Comunicação",
            role: "security",
            email: "gomes@gmail.com",
            pic: "",
            bio: "A smart person",
            lattes: "",
            linkedin: "meu linked-in",
            active: false
        },
        {
            key: "desousa",
            name: "Rafael T. de Sousa Júnior",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "franciscocaldasf",
            name: "Francisco L. de Caldas Filho",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "fabiomendonca",
            name: "Fábio L. L. de Mendonça",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "marcosandrade",
            name: "Marcos B. Andrade",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "matheusmonteiro",
            name: "Matheus S. Monteiro",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "patrao",
            name: "Rafael L. Patrão",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "justino",
            name: "Bruno Justino G. Praciano",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "robsonalbuquerde",
            name: "robsonalbuquerde",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "lustosa",
            name: "João Paulo C. L. da Costa",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "cassioribeiro",
            name: "Cassio Fabius C. Ribeiro",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "fiuza",
            name: "João F. de Alencastro",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "maristelaholanda",
            name: "Maristela Holanda",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "thalessperling",
            name: "Thales L. von Sperling",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "dayannecunha",
            name: "dayannecunha",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "mateuszanatta",
            name: "mateuszanatta",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "brunodutra",
            name: "Bruno V. Dutra",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "brunofranca",
            name: "Bruno de A. França",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "kfouri",
            name: "Guilherme de O. Kfouri",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "gersonsilva",
            name: "Gerson do N. Silva",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "tribouilet",
            name: "João Tribouilet M. de Menezes",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "demetriosilvaf",
            name: "demetriosilvaf",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "barenco",
            name: "Cláudia J. Barenco Abbas",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "ednacanedo",
            name: "Edna D. Canedo",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "rodrigorocha",
            name: "Rodrigo L. Rocha",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "rubenhuacarpuma",
            name: "Ruben C. Huacarpuma",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "ingridaraujo",
            name: "Ingrid P. Araújo",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "fabiobuiati",
            name: "Fábio Buiati",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "luisvillalba",
            name: "Luis Javier García Villalba",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "taikim",
            name: "Tai-Hoon Kim",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "caiosilva",
            name: "Caio C. M. Silva",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "samuelalmeida",
            name: "Samuel Almeida",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "poletti",
            name: "João Victor Poletti",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "felipemachado",
            name: "Felipe D. Machado",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "sergiolifschitz",
            name: "Sérgio Lifschitz",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "hiroferreira",
            name: "Hiro G. C. Ferreira",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "giozza",
            name: "William F. Giozza",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "flavioelias",
            name: "Flávio Elias G. de Deus",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },

        {
            key: "danielsilva",
            name: "Daniel A. da Silva",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "josetorres",
            name: "José Alberto S. Torres",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },
        {
            key: "alexandrepinheiro",
            name: "Alexandre Pinheiro",
            area: "",
            role: "",
            email: "",
            pic: "",
            bio: "",
            lattes: "",
            linkedin: "",
            active: false
        },

        // template
        // {
        //     key: "x",
        //     name: "",
        //     area: "",
        //     role: "",
        //     email: "",
        //     pic: "",
        //     bio: "",
        //     lattes: "",
        //     linkedin: "",
        //     active: false
        // },
    ]
  export default Members
